### ISSUE TITLE
Transfer cost not getting charged - MC1710 - Forge1206

### ISSUE THREAD

**Issue by SyiSeiko** [enhanced-portals/enhanced-portals#141]
Portal can be used for free when teleporting before 10k/s power cost can trigger. Eg. Using redstone interface output on entity touch portal and input remove portal, then activating portal while standing in it.

Transfer power fee doesn't seem to be getting charged at all. Only the constant 10k/s drain of having active portals.

**Comment by ShadedDimension** [comment]
There is no 'transfer power fee', currently there is only the drain every second. It will be changing soon (#182).
