### ISSUE TITLE
Lag on player connection

### ISSUE THREAD

**Issue by LemADEC** [enhanced-portals/enhanced-portals#174]
When a player connects, a lag spike is observed in Opis:
cpw.mods.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent	EnhancedPortals	enhancedportals.network.LogOnHandler	LogOnHandler.onLogIn	1	68820.768 µs

**Comment by ShadedDimension** [comment]
This was caused by some odd update checking code. Client-side code was being run server-side.
