### ISSUE TITLE
Compatibility Issue with ThermalExpansion?

### ISSUE THREAD

**Issue by katzenpapst** [enhanced-portals/enhanced-portals#181]
Hi,

just attempted to add Enhanced Portals to my installation. As soon as I do this, no world can be loaded, Minecraft dies with this error:

> java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class thermalexpansion.util.crafting.PulverizerManager$ComparableItemStackPulverizer id= 667594137 hashCode= 407 toString= thermalexpansion.util.crafting.PulverizerManager$ComparableItemStackPulverizer@667594137{m:0, i:com.teammetallurgy.metallurgy.metals.MetalItem@67960309, v:5025}; object #2 =class thermalexpansion.util.crafting.PulverizerManager$ComparableItemStackPulverizer id= 1475670482 hashCode= 329318400 toString= thermalexpansion.util.crafting.PulverizerManager$ComparableItemStackPulverizer@1475670482{m:0, i:com.teammetallurgy.metallurgy.metals.MetalItem@67960309, v:5025}

A more complete error is here: http://pastebin.com/PAzJq8c8

This thermal expansion/cofh stuff is used:
ThermalExpansion-[1.7.10]4.0.0B8-23.jar
ThermalFoundation-[1.7.10]1.0.0RC1-13.jar
CoFHCore-[1.7.10]3.0.0B9-40.jar
The full mod list is here: http://pastebin.com/MUdxBdg8

Tried on Win7, Minecraft 1.7.10 of course, and several versions of Java from 1.7 to 1.8.

Googling the error gave me this:
http://forum.feed-the-beast.com/threads/1-7-10-let-it-end.51948/page-21#post-861549
and, maybe more informatively, this:
https://github.com/squeek502/VeganOption/issues/7
These imply that this can be indeed caused by other mods than thermal expansion. Maybe the fix in that vegan mod can help you, too?

**Comment by ShadedDimension** [comment]
After some digging, the issue was originally caused by the ComparableItemStack in CoFHLib, and was [fixed here](https://github.com/CoFH/CoFHLib/commit/241051d9e3b47a46abe7d7f6d3b8d85e7f1559bd).

I have no idea how you only get it when EP is installed. The error log has no mention of anything EP related, only CoFHCore and Metallurgy, so this means if it is caused by EP then I have no idea where to begin to start to look. I'm not shipping that part of CoFHLib and I don't seem to be registering things where they're not supposed to be.

Regardless, I'll take a look and see if I can reproduce this.

**Comment by katzenpapst** [comment]
Weird...
Hm wait. I don't have CofhLib. Maybe that's the error. Why does it work anyway, though?

**Comment by ShadedDimension** [comment]
Originally CoFHLib was a slice of CoFHCore that was made open source for people to use. Now it seems that CoFHCore is open source too? I've been away from modding for a little while so that confuses me, but essentially CoFHLib is part of CoFHCore.

**Comment by katzenpapst** [comment]
Well, just downloading cofhlib and dropping it into the mods folder had no effect whatsoever.

Also, the version of cofhcore that I have (CoFHCore-[1.7.10]3.0.0B9-40.jar) seems to be newer than that commit. Still trying to get the newest alpha versions of that stuff to work right now.

**Comment by katzenpapst** [comment]
Can be closed. The new TE (ThermalExpansion-[1.7.10]4.0.0RC1-119.jar) fixes it
