### ISSUE TITLE
Dialing device not behaving like other portal frame blocks

### ISSUE THREAD

**Issue by davkas2005** [enhanced-portals/enhanced-portals#185]
The Portal Controller and Redstone Interface GUI are only accessible using the wrench, and when not wearing the glasses they blend into the rest of the portal frame.

The Dialing Device can be accessed with an empty hand, and does not blend in when not wearing the glasses.

**Comment by kzarius** [comment]
This is intended. If Controllers and Redstone interfaces could be changed without added gear, then any user would be presented with these block options. Dialing devices, however, are meant to be used by anyone who accesses the portal.
