### ISSUE TITLE
Portals won't listen to Module Manipulator

### ISSUE THREAD

**Issue by helleputter** [enhanced-portals/enhanced-portals#191]
I created 3 portals. 2 in the overworld 1 in the nether. They all got the Particle Destroyer Module wich seems to work as long as im in the overworld. When traveling to the nether and back the particles are back and the module isn't work unless i click it with a wrench.... Is this a bug??

**Comment by mickdekkers** [comment]
I have 2 portals set up, both in the Overworld on the same network. I put a silencer and particle destroyer in the module manipulators on both the portals. It works fine until I step through either portal, at which point the portal I come out of starts producing sound and particles again. Turning the portal off and on again does not fix the issue.

**Comment by Anomerly** [comment]
I have the same issue when moving between dimensions, though I am traveling to an AE2 SP Cell dimension and back.

**Comment by Alz454** [comment]
Fixed in https://github.com/enhancedportals/enhancedportals/commit/3811532e001d8567945a50bd4abe24e2db2714f3
